# Generated by Django 4.2.3 on 2023-07-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('onshore', models.BooleanField()),
                ('preferred_language', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('country_of_residence', models.CharField(max_length=50)),
                ('highest_education', models.CharField(max_length=50)),
                ('how_did_you_hear', models.CharField(choices=[('social/facebook', 'Social Media (Facebook)'), ('social/instagram', 'Social Media (Instagram)'), ('social/tiktok', 'Social Media (TikTok)'), ('eDm', 'Email Marketing (EDM)'), ('expo', 'Expo or Event'), ('referral', 'Referral'), ('websearch', 'Web Search'), ('advertising/print', 'Advertising (Print)'), ('advertising/tv', 'Advertising (TV)'), ('advertising/cinema', 'Advertising (Cinema)'), ('advertising/radio', 'Advertising (Radio)'), ('advertising/outdoor', 'Advertising (Outdoor)'), ('advertising/online', 'Advertising (Online)'), ('school', 'School'), ('other', 'Other')], max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('concentration', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('campus', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('study_level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('intakes', models.CharField(max_length=100)),
                ('entry_requirements', models.TextField()),
                ('ielts_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ielts_no_band_less_than', models.DecimalField(decimal_places=2, max_digits=4)),
                ('toefl_score', models.IntegerField()),
                ('toefl_no_band_less_than', models.IntegerField()),
                ('pte_score', models.IntegerField()),
                ('pte_no_band_less_than', models.CharField(max_length=10)),
                ('application_deadline', models.DateField(null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('yearly_tuition_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship_available', models.BooleanField(default=False, null=True)),
                ('scholarship_detail', models.TextField(blank=True, null=True)),
                ('backlog_range', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('esl_elp_detail', models.TextField(blank=True, null=True)),
                ('application_mode', models.CharField(max_length=100, null=True)),
                ('application', models.CharField(max_length=100, null=True)),
                ('det_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('student', 'Student'), ('superuser', 'Superuser')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intended_area_of_study', models.CharField(max_length=100)),
                ('intended_course_level', models.CharField(max_length=50)),
                ('courses_and_fields_comments', models.TextField()),
                ('career_paths', models.TextField()),
                ('intended_institutions', models.TextField()),
                ('intended_intake_quarter', models.CharField(max_length=50)),
                ('intended_intake_year', models.IntegerField()),
                ('intended_intake_comments', models.TextField()),
                ('funding_source', models.CharField(max_length=100)),
                ('intended_destination_1', models.CharField(max_length=100)),
                ('intended_destination_2', models.CharField(max_length=100)),
                ('intended_destination_3', models.CharField(max_length=100)),
                ('intended_destination_comments', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='University',
            field=models.ManyToManyField(to='student.university'),
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode_zipcode', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='personal_images/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='LeadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('pending', 'Pending')], max_length=50)),
                ('prospect_rating', models.CharField(choices=[('not_rated', 'Not Rated'), ('1_star', '1 Star'), ('2_star', '2 Star'), ('3_star', '3 Star')], max_length=50)),
                ('preference_appointment_date', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(max_length=100)),
                ('candidate_comments', models.TextField()),
                ('signup_country', models.CharField(max_length=100)),
                ('signup_city', models.CharField(max_length=100)),
                ('signup_state_province', models.CharField(max_length=100)),
                ('signup_ip', models.GenericIPAddressField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
                ('campaign_name', models.CharField(max_length=100)),
                ('form_id', models.IntegerField()),
                ('form_name', models.CharField(max_length=100)),
                ('ad_id', models.IntegerField()),
                ('ad_name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education', models.CharField(choices=[('highschool', 'High School'), ('language_pathway', 'Language Pathway'), ('undergraduate-foundation', 'Undergraduate Foundation'), ('undergraduate-certificate', 'Undergraduate Certificate'), ('undergraduate-diploma', 'Undergraduate Diploma'), ('undergraduate-associate_degree', 'Undergraduate Associate Degree'), ('undergraduate-bachelor', 'Undergraduate Bachelor'), ('postgraduate-certificate', 'Postgraduate Certificate'), ('postgraduate-diploma', 'Postgraduate Diploma'), ('masters', "Master's Degree"), ('doctrate_phd', 'Doctorate/PhD')], max_length=50)),
                ('country_where_study_completed', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
