# Generated by Django 4.2.3 on 2023-07-06 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(blank=True, null=True)),
                ('tasks', models.CharField(max_length=50)),
                ('timeline', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('phase', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('active_team', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('agent', 'Agent'), ('student', 'Student')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='student.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('application_status', models.CharField(max_length=50)),
                ('save_date', models.DateField()),
                ('shortlisted_date', models.DateTimeField()),
                ('first_submitted', models.DateField()),
                ('declaration', models.BooleanField(default=False)),
                ('medical_condition', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='academicachievement',
            name='completed_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='academicachievement',
            name='result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='academicachievement',
            name='school_institute_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='academicachievement',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='academicachievement',
            name='title_of_your_course',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='ApplicationStage',
            field=models.CharField(choices=[('submitted', 'Submitted to Adventus'), ('lodged', 'Lodged with Institutions'), ('offers_received', 'Offers Received'), ('visas_granted', 'Visas Granted'), ('students_commenced', 'Students Commenced'), ('students_deferred', 'Students Deferred')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadtracking',
            name='preference_appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='University',
            field=models.ManyToManyField(related_name='students', to='student.university'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='student',
            field=models.ManyToManyField(to='student.student'),
        ),
        migrations.AddField(
            model_name='agent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='student.customuser'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='student.customuser'),
            preserve_default=False,
        ),
    ]
