# Generated by Django 4.2.3 on 2023-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_university_campus_alter_university_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='backlog_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='scholarship_available',
            field=models.BooleanField(default=False),
        ),
    ]
