# Generated by Django 4.2.3 on 2023-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='scholarship_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
