# Generated by Django 4.2.3 on 2023-07-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_university_scholarship_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
