# Generated by Django 4.2.3 on 2023-07-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_university_pte_no_band_less_than'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='pte_no_band_less_than',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
