# Generated by Django 4.2.3 on 2023-07-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_university_pte_no_band_less_than'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='yearly_tuition_fees',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
