# Generated by Django 4.2.3 on 2023-07-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_university_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='application_deadline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
